language: java
jdk:
  - oraclejdk8

env:
  - TERM=dumb
  
before_install:
 - chmod +x gradlew

install: ./gradlew --version

script: 
  - ./gradlew --continue
  - ./gradlew tasks
  - ./gradlew export.com.acme.prime.eval
